const CLIENT_ID = "a4b9f7aff9214596973c1f8b9c8c89e4";
const REDIRECT_URI = "https://paulajfsousa-boop.github.io/musicfit/";
const SCOPES = ["streaming","user-read-email","user-read-private","user-read-playback-state","user-modify-playback-state"];

let accessToken = null, player = null, deviceId = null, currentTrack = null, currentPosition = 0, currentDuration = 0, cues=[], trackBpm = null;
let lessonTracks = [], activeLessonIndex = -1, lessonPlaying = false, switchingTrack = false, playerPaused = true;

function base64url(bytes) { return btoa(String.fromCharCode(...bytes)).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,''); }
async function sha256(s) { return new Uint8Array(await crypto.subtle.digest('SHA-256', new TextEncoder().encode(s))); }
function randomString(n=64) { const a='ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-._~'; let s=''; crypto.getRandomValues(new Uint32Array(n)).forEach(v=>s+=a[v%a.length]); return s; }
async function login() { const verifier=randomString(64); sessionStorage.setItem('verifier',verifier); const challenge=base64url(await sha256(verifier)); const p=new URLSearchParams({response_type:'code', client_id:CLIENT_ID, scope:SCOPES.join(' '),redirect_uri:REDIRECT_URI, code_challenge_method:'S256', code_challenge:challenge}); location.href='https://accounts.spotify.com/authorize?'+p.toString(); }
async function exchangeCode(code) { const verifier=sessionStorage.getItem('verifier'); const body=new URLSearchParams({client_id:CLIENT_ID, grant_type:'authorization_code', code, redirect_uri:REDIRECT_URI, code_verifier:verifier}); const r=await fetch('https://accounts.spotify.com/api/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body}); const d=await r.json(); if(!r.ok) throw new Error(d.error_description||d.error||'Falha no login'); sessionStorage.setItem('access_token',d.access_token); sessionStorage.setItem('expires_at',Date.now()+d.expires_in*1000); accessToken=d.access_token; history.replaceState({},'',REDIRECT_URI); }
function tokenValid() { return sessionStorage.getItem('access_token') && Number(sessionStorage.getItem('expires_at')||0)>Date.now()+30000; }
async function initAuth() { const params=new URLSearchParams(location.search); const code=params.get('code'); if(code) await exchangeCode(code); if(tokenValid()) {accessToken=sessionStorage.getItem('access_token');document.getElementById('spotifyArea').classList.remove('hidden');document.getElementById('loginBtn').classList.add('hidden');document.getElementById('logoutBtn').classList.remove('hidden');document.getElementById('authStatus').textContent='Ligado ao Spotify.';loadSpotifySDK();} }
document.getElementById('loginBtn').onclick=login;
document.getElementById('logoutBtn').onclick=()=>{sessionStorage.clear();location.href=REDIRECT_URI;};
function loadSpotifySDK() { if(document.getElementById('spotify-sdk')) return; const s=document.createElement('script'); s.id='spotify-sdk'; s.src='https://sdk.scdn.co/spotify-player.js'; document.body.appendChild(s); }
window.onSpotifyWebPlaybackSDKReady = () => { player = new Spotify.Player({name:'MusicFit Cue',getOAuthToken: cb => cb(accessToken),volume:0.8}); player.addListener('ready', ({device_id})=>{deviceId=device_id;document.getElementById('playerStatus').textContent='Player Spotify pronto.';}); player.addListener('not_ready',()=>document.getElementById('playerStatus').textContent='Player Spotify indisponível.'); player.addListener('initialization_error',e=>document.getElementById('playerStatus').textContent='Erro: '+e.message); player.addListener('authentication_error',e=>document.getElementById('playerStatus').textContent='Erro de autenticação: '+e.message); player.addListener('account_error',e=>document.getElementById('playerStatus').textContent='A reprodução Web Playback requer Spotify Premium.'); player.addListener('player_state_changed',state=>{ if(!state) return; playerPaused=state.paused; updateRunPlayPause(); currentPosition=state.position/1000; currentDuration=state.duration/1000; updateSeekUI(); const tw=state.track_window.current_track; currentTrack={uri:tw.uri,id:tw.id,name:tw.name,artist:tw.artists.map(a=>a.name).join(', '),image:tw.album.images?.[0]?.url||'',duration:state.duration/1000}; showTrack(); updateRun(); if(lessonPlaying && !switchingTrack){ const remaining=(state.duration-state.position)/1000; if(state.paused && state.position===0 && activeLessonIndex>=0){} else if(remaining<=0.35){advanceLessonTrack();}} }); player.connect(); };
async function api(path, options={}) { const r=await fetch('https://api.spotify.com/v1'+path,{...options,headers:{Authorization:'Bearer '+accessToken,'Content-Type':'application/json',...(options.headers||{})}}); if(r.status===204) return null; const text=await r.text(); let d=null; if(text){try{d=JSON.parse(text);}catch(e){d=text;}} if(!r.ok){const msg=(d&&typeof d==='object'&&d.error?.message)?d.error.message:(typeof d==='string'?d:'Erro Spotify');throw new Error(msg);} return d; }
document.getElementById('searchBtn').onclick=async()=>{ const q=document.getElementById('searchInput').value.trim(); if(!q)return; const d=await api('/search?type=track&limit=8&q='+encodeURIComponent(q)); const box=document.getElementById('results'); box.innerHTML=''; d.tracks.items.forEach(t=>{ const div=document.createElement('div'); div.className='track'; div.innerHTML=`<img class="cover" src="${t.album.images?.[1]?.url||t.album.images?.[0]?.url||''}"><div class="trackmeta"><b>${esc(t.name)}</b><span>${esc(t.artists.map(a=>a.name).join(', '))}</span></div><button>Escolher</button>`; div.querySelector('button').onclick=()=>selectTrack(t); box.appendChild(div); }); };
function selectTrack(t) { currentTrack={uri:t.uri,id:t.id,name:t.name,artist:t.artists.map(a=>a.name).join(', '),image:t.album.images?.[0]?.url||'',duration:t.duration_ms/1000}; currentPosition=0; currentDuration=t.duration_ms/1000; cues=[]; renderCues(); showTrack(); updateSeekUI(); }
function showTrack() { if(!currentTrack)return; document.getElementById('trackName').textContent=currentTrack.name; document.getElementById('artistName').textContent=currentTrack.artist; document.getElementById('cover').src=currentTrack.image||''; }
document.getElementById('playBtn').onclick=async()=>{ if(lessonTracks.length){if(activeLessonIndex<0) activeLessonIndex=0;lessonPlaying=true;if(!currentTrack || currentTrack.id!==lessonTracks[activeLessonIndex].track?.id){loadLessonTrack(activeLessonIndex,true);return;}} if(!currentTrack) return alert('Primeiro escolhe uma música.'); if(!deviceId) return alert('O leitor Spotify ainda não está pronto. Espera alguns segundos e tenta novamente.'); try{ if(player && player.activateElement) await player.activateElement(); document.getElementById('playerStatus').textContent='A iniciar reprodução...'; await api('/me/player/play?device_id='+encodeURIComponent(deviceId),{method:'PUT',body:JSON.stringify({uris:[currentTrack.uri],position_ms:Math.floor(currentPosition*1000)})}); document.getElementById('playerStatus').textContent='A reproduzir no MusicFit Cue.';}catch(e){document.getElementById('playerStatus').textContent='Erro ao reproduzir: '+e.message;alert('Não consegui iniciar a música: '+e.message);} };
document.getElementById('pauseBtn').onclick=()=>api('/me/player/pause',{method:'PUT'});
async function seekTo(seconds){ if(!currentTrack) return; const max=currentDuration||0; const target=Math.max(0,Math.min(Number(seconds)||0,max)); currentPosition=target; try{if(player&&typeof player.seek==='function'){await player.seek(Math.floor(target*1000));}else{await api('/me/player/seek?position_ms='+Math.floor(target*1000),{method:'PUT'});}document.getElementById('playerStatus').textContent='Posição: '+fmtClock(target);}catch(e){document.getElementById('playerStatus').textContent='Erro ao mudar de posição: '+e.message;} updateRun(); updateSeekUI();}
document.getElementById('restartBtn').onclick=()=>seekTo(0); document.getElementById('back10Btn').onclick=()=>seekTo(currentPosition-10); document.getElementById('forward10Btn').onclick=()=>seekTo(currentPosition+10);
const seekBar=document.getElementById('seekBar'); let draggingSeek=false; seekBar.addEventListener('pointerdown',()=>draggingSeek=true); seekBar.addEventListener('pointerup',async()=>{draggingSeek=false;await seekTo(parseFloat(seekBar.value));}); seekBar.addEventListener('change',async()=>{draggingSeek=false;await seekTo(parseFloat(seekBar.value));}); seekBar.addEventListener('input',()=>{const val=parseFloat(seekBar.value)||0;document.getElementById('seekTime').textContent=fmtClock(val)+' / '+fmtClock(currentDuration||0);});
function fmtClock(t){if(!isFinite(t))return'0:00';const m=Math.floor(t/60);const s=Math.floor(t%60).toString().padStart(2,'0');return m+':'+s;} function updateSeekUI(){if(!draggingSeek){seekBar.max=Math.max(0,currentDuration||0);seekBar.value=Math.max(0,Math.min(currentPosition||0,currentDuration||0));}document.getElementById('seekTime').textContent=fmtClock(currentPosition||0)+' / '+fmtClock(currentDuration||0);} setInterval(async()=>{if(player){const st=await player.getCurrentState().catch(()=>null);if(st){currentPosition=st.position/1000;currentDuration=st.duration/1000;updateSeekUI();updateRun();if(lessonPlaying&&!switchingTrack&&currentDuration>0&&(currentDuration-currentPosition)<=0.35){advanceLessonTrack();}}}},250);
function fmt(t){const m=Math.floor(t/60),s=Math.floor(t%60).toString().padStart(2,'0'),d=Math.floor((t%1)*10);return `${m}:${s}.${d}`;} function esc(s){return(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));}